Property 'mutedSegmentData' must allow null
twurple/twurple pull request #389
Opened 2022-08-31 09:41 UTC by bishil06

Type:  #Bugfix

Fixes: #388 

`mutedSegmentData`
Array of muted segments in the video.
If there are no muted segments, the value will be `null`.
[twitch reference](https://dev.twitch.tv/docs/api/reference#get-videos)

my solution 
```ts
muted_segments: HelixVideoMutedSegmentData[];  // -> muted_segments: HelixVideoMutedSegmentData[] | null; 
```

2022-08-31 12:26 UTC, d-fischer requested changes
Apart from the proposed direct changes, this PR should probably be on the `versions/5.2` branch.

2022-08-31 12:26 UTC, d-fischer commented on packages/api/src/api/helix/video/HelixVideo.ts
> +	get mutedSegmentData(): HelixVideoMutedSegmentData[] | null {
This is an unnecessary breaking change. I'd rather return an empty array if Twitch returns null.

2022-08-31 12:26 UTC, d-fischer commented on packages/api/src/api/helix/video/HelixVideo.ts
> +		if (this[rawDataSymbol].muted_segments === null) {
This is a prime example for usage of null coalescing / optional chaining.

2022-09-01 04:07 UTC, bishil06 commented
Modified to return `[]` using the nullish coalescing operator if `mutedSegmentData` is `null`

https://github.com/twurple/twurple/blob/058d669ed0bc24d05b833a8bc01963ab4f10f97d/packages/api/src/api/helix/video/HelixVideo.ts#L218-L220

2022-09-04 13:21 UTC, d-fischer commented
Why did you undo the change to the internal data interface? It should be true to the original Twitch data as exactly as possible. If Twitch can return null, it should include null. This does *not* affect the getter, and indeed resolves the linter issue shown in the build log.

2022-09-07 05:40 UTC, bishil06 commented
It was my mistake. I'm sorry

2022-09-07 07:40 UTC, d-fischer requested changes
Also still not on the version branch.

2022-09-07 07:40 UTC, d-fischer commented on packages/api/src/api/helix/video/HelixVideo.ts
> +		return this[rawDataSymbol].muted_segments === null ? [] : this[rawDataSymbol].muted_segments;
Again, optional chaining here.

2022-09-07 15:23 UTC, closed without merging