feat(api): use string literal type for broadcasterType in HelixUser
twurple/twurple pull request #421
Opened 2022-11-27 14:22 UTC by StimulCross

Type: Improvement
Fixes: #420

Uses a string literal type as the return type of `broadcasterType` member of HelixUser.

2022-11-27 20:51 UTC, d-fischer commented
This is a breaking change and as such will have to wait until 6.0 development will start.

2022-12-13 22:08 UTC, d-fischer requested changes

2022-12-13 22:08 UTC, d-fischer commented on packages/api/src/api/helix/user/HelixUser.ts
> +	get broadcasterType(): HelixBroadcasterType {
This type now needs to be imported since it moved out of the file.

2022-12-13 22:23 UTC, StimulCross commented
Changes made

2022-12-13 23:23 UTC, d-fischer approved these changes

2022-12-13 23:23 UTC, merged