Proper Request End
twurple/twurple pull request #525
Opened 2023-10-06 13:38 UTC by Digital39999

Type: Bugfix
Description: When using Express which has 404/error handlers, Twurple will just continue the request even if it ended.

2023-10-06 18:03 UTC, d-fischer requested changes

2023-10-07 05:40 UTC, Digital39999 commented on packages/eventsub-http/src/EventSubHttpBase.ts
> +				return;
Pretty much yes, those returns are there for code equality.

2023-10-10 18:47 UTC, Digital39999 commented
@d-fischer what now about this pr, can you merge it, or do own commit, we'd really need this in release versiom.

2023-10-10 18:48 UTC, d-fischer commented
You resolved the conversation without actually changing anything. Additionally, the checks fail.

2023-10-10 18:57 UTC, Digital39999 commented
But there's nothing to change in conversation? I removed the next(), and added returns to make code equal as in other places, ei. [1.](https://github.com/twurple/twurple/blob/main/packages/eventsub-http/src/EventSubHttpBase.ts#L157), [2.](https://github.com/twurple/twurple/blob/main/packages/eventsub-http/src/EventSubHttpBase.ts#L171), [3.](https://github.com/twurple/twurple/blob/main/packages/eventsub-http/src/EventSubHttpBase.ts#L196), and so on..

2023-10-10 19:01 UTC, Digital39999 commented
And this package is hell to use prettier with, literally all files are marked with warns.

2023-10-10 19:04 UTC, d-fischer commented
> And this package is hell to use prettier with, literally all files are marked with warns.

This package has its own prettier config and even runs prettier on every single commit and succeeds. The only way this could be true is if you are using a config that is not our config, which is probably your own problem.

2023-10-10 19:07 UTC, d-fischer commented
> But there's nothing to change in conversation?

If I tell you something is useless, and even CI tells you it's useless, arguing against it is not gonna help at all.

2023-10-10 19:10 UTC, d-fischer commented
After the last force push, it doesn't seem like there is any change in this PR anymore, other than faulty version bumps. I'm closing this, you may open a new PR if you want to move this issue forward and get credit for it. Otherwise, I'm just gonna properly fix it myself when I have the time.

2023-10-10 19:10 UTC, closed without merging

2023-10-10 19:11 UTC, Digital39999 commented
I just synced it with origin and wanted to fix it in branch you redirected me to. I'll open a new issue.