feat(eventsub): add automod events
twurple/twurple pull request #578
Opened 2024-05-27 08:54 UTC by StimulCross

Type: Feature
Fixes: #569 

Implemented subscription types:
- [automod.message.hold](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessagehold)
- [automod.message.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessageupdate)
- [automod.settings.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodsettingsupdate)
- [automod.terms.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodtermsupdate)
- [channel.chat.user_message_hold](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_hold)
- [channel.chat.user_message_update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_update)

Tested this manually using `yalc`. 

Ignore discrepancies with the documentation. As is often the case on Twitch, the documentation doesn't match the actual payload.

2024-05-30 06:31 UTC, StimulCross commented
I just noticed [channel.chat.user_message_hold](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_hold) and  [channel.chat.user_message_update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_update) topics may additionally require `user:bot` scope if an app access token is used. I don't know how to handle this properly.

2024-08-26 16:29 UTC, d-fischer requested changes

2024-08-26 16:29 UTC, d-fischer commented on packages/eventsub-base/src/index.ts
> +export type { EventSubChannelChatUserMessageUpdateEvent } from './events/EventSubChannelChatUserMessageUpdateEvent';
Please don't `export type` any of the event classes. Use regular exports instead.

2024-09-08 18:37 UTC, d-fischer approved these changes

2024-09-08 18:37 UTC, merged